eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: "Client2"
      profile: development
  application:
    name: <Client2>
message: Hello from Client2!
