eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: "Client1"
      profile: development
  application:
    name: "Client1"
message: Hello from Client1!
